### ISSUE TITLE
missing config details

### ISSUE THREAD

**Issue by bkyerv** [Sebusml/landing-page-amplify#1]
it says some config details are missing. are these details similar to env variables and you intentionally decided not to publish them on github?
![image](https://user-images.githubusercontent.com/87478959/150976302-b5f3cf2f-9c24-42ce-988d-5b6d69ee32f9.png)
![Uploading Screenshot from 2022-01-25 18-17-37.png…]()

**Comment by Sebusml** [comment]
Yeah, `aws-exports` contains aws account secrets, there should be a way to get you started with amplify-cli in your local env. I can create you an user in AY's aws account so that we can share the same data.
